package com.vroozi.customerui.acl.model;

/**
 * User: SURYA MANDADAPU
 * Date: 11/30/12
 * Time: 10:41 AM
 * Completed by Ara Tatous
 */
public enum Permission {
    // landing Page
    VIEW_HOME_CARDS,
    VIEW_ANNOUNCEMENT,
    VIEW_SHOPPER_VIEW,


    // Message Center
    VIEW_MESSAGE,
    CREATE_MESSAGE,
    SEND_MESSAGE,

    // Custom Fields
    VIEW_CUSTOM_FIELDS,
    CREATE_CUSTOM_FIELDS,
    EDIT_CUSTOM_FIELDS,
    DELETE_CUSTOM_FIELDS,
    ACTIVATE_CUSTOM_FIELDS,
    DEACTIVATE_CUSTOM_FIELDS,

    // Catalogs
    VIEW_CATALOG,
    CREATE_CATALOG,
    EDIT_CATALOG,
    DELETE_CATALOG,
    REJECT_CATALOG,
    APPROVE_CATALOG,
    PUBLISH_CATALOG,
    DEACTIVATE_CATALOG,
    OFFLINE_CATALOG,
    VIEW_WEB_SEARCH_USER,
    CHANGE_SUPPLIER,
    // Catalog items
    CREATE_ITEM,
    EDIT_ITEM,
    DELETE_ITEM,
    APPROVE_ITEM,
    REJECT_ITEM,
    PUPLISH_ITEM,
    UNPUBLISH_ITEM,
    
    //REPORTS
    VIEW_REPORTS,
    // Supplier
    VIEW_SUPPLIER,
    CREATE_SUPPLIER,
    EDIT_SUPPLIER,
    DELETE_SUPPLIER,
    ACTIVATE_SUPPLIER,
    DEACTIVATE_SUPPLIER,
    VIEW_SUPPLIER_ATTRIBUTE,
    CREATE_SUPPLIER_ATTRIBUTE,
    EDIT_SUPPLIER_ATTRIBUTE,
    DELETE_SUPPLIER_ATTRIBUTE,
    ACTIVATE_SUPPLIER_ATTRIBUTE,
    DEACTIVATE_SUPPLIER_ATTRIBUTE,

    // User Account Settings
    VIEW_ACCOUNT_SETTINGS,
    EDIT_ACCOUNT_SETTINGS,

    // User Management
    VIEW_MASTER_ADMIN,
    CRETAE_MASTER_ADMIN,
    DELETE_MASTER_ADMIN,
    EDIT_MASTER_ADMIN,
    VIEW_ADMIN,
    EDIT_ADMIN,
    CREATE_ADMIN,
    DELETE_ADMIN,
    VIEW_APPROVER,
    CREATE_APPROVER,
    EDIT_APPROVIER,
    DELETE_APPROVER,
    VIEW_BUYER,
    CREATE_BUYER,
    EDIT_BUYER,
    DELETE_BUYER,
    VIEW_SEARCH_USER,
    CREATE_SEARCH_USER,
    EDIT_SEARCH_USER,
    DELETE_SEARCH_USER,
    VIEW_SHOPPER,
    CREATE_SHOPPER,
    EDIT_SHOPPER,
    DELETE_SHOPPER,
    EDIT_SHOPPER_VIEW_ONLY,
    
    //Content View
    VIEW_CONTENT_VIEW,
    CREATE_CONTENT_VIEW,
    EDIT_CONTENT_VIEW,
    DELETE_CONTENT_VIEW,
    ACTIVATE_CONTENT_VIEW,
    DEACTIVATE_CONTENT_VIEW,
    
    //Content View Group
    VIEW_CONTENT_VIEW_GROUP,
    CREATE_CONTENT_VIEW_GROUP,
    EDIT_CONTENT_VIEW_GROUP,
    DELETE_CONTENT_VIEW_GROUP,
    ACTIVATE_CONTENT_VIEW_GROUP,
    DEACTIVATE_CONTENT_VIEW_GROUP,
    
    // Data Mapping
    VIEW_DATA_MAPPING,
    CREATE_DATA_MAPPING,
    EDIT_DATA_MAPPING,
    DELETE_DATA_MAPPING,

    // Company Setting
    VIEW_COMPANY_SETTING,
    EDIT_COMPANY_SETTING,
    UPLOAD_COMPANY_LOGO,
    UPLOAD_NO_IMAGE_LOGO,
    EDIT_HOME_PAGE_CARDS,
    VIEW_FAQ,
    CREATE_FAQ,
    EDIT_FAQ,
    DELETE_FAQ,
    VIEW_POLICY,
    CREATE_POLICY,
    EDIT_POLICY,
    DELETE_POLICY,
    VIEW_CONACT_US,
    CREATE_CONACT_US,
    EDIT_CONACT_US,
    DELETE_CONACT_US,
    VIEW_APPROVAL_WORKFLOW,
    EDIT_APPROVAL_WORKFLOW,
    VIEW_USER_NAME,
    VIEW_PASSWORD,
    // Header
    SEARCH,

    // Navigation Header
    VIEW_USER_MANAGEMENT,
    VIEW_PURCHASE_REQUEST,
    VIEW_HELP,

    //CONTENT ACCESS
    VIEW_CONTENT_ACCESS,
    //UOM Mapping
    VIEW_UOM_MAPPING,
    VIEW_CURRENCY_MAPPING,
  VIEW_CONTENT_SHARE_MAPPING
}
